stages:
 - build
 - test
 - deploy

Debian:
  image: debian:latest
  stage: build
  before_script:
    - apt-get update -qq
    - env DEBIAN_FRONTEND=noninteractive apt-get install -y -qq git autoconf automake libtool gettext cvs make texinfo texlive texlive-generic-recommended texlive-extra-utils texlive-font-utils help2man gtk-doc-tools libglib2.0-dev dblatex valgrind dia libidn11-dev libntlm0-dev libgnutls28-dev libkrb5-dev gengetopt gperf
  script:
    - make autoreconf
    - ./configure --enable-gcc-warnings --disable-silent-rules --enable-gtk-doc --enable-gtk-doc-pdf
    - make
    - make check || (find . -name test-suite.log -exec cat {} +; exit 1)
    - make dist
    - sha224sum gsasl-*.tar.gz
  artifacts:
    expire_in: 2 weeks
    paths:
      - gsasl-*.tar.gz
