Debian GNU/Linux build:
  tags:
    - glr1
  before_script:
    - sudo apt-get install -y git autoconf automake libtool gettext cvs make
    - sudo apt-get install -y texinfo texlive texlive-generic-recommended texlive-extra-utils
    - sudo apt-get install -y help2man gtk-doc-tools valgrind
    - sudo apt-get install -y dia libgnutls-dev gengetopt gperf liblasso3-dev
    - make bootstrap CFGFLAGS="--enable-gcc-warnings --disable-silent-rules"
  script:
    - (make && make check) || (cat *.log test-suite.log; exit 1)
